//
//  SchemaDiff.swift
//  mactable
//
//  Pure value transform that compares two `[TableInfo]` snapshots and
//  emits a list of structural deltas tagged for git-style highlighting.
//

import Foundation

struct SchemaDelta: Identifiable, Hashable {
    enum Kind: Hashable {
        case added       // Right has table; Left does not
        case removed     // Left has table; Right does not
        case modified    // Both, but row count differs (signal only)
        case unchanged
    }
    let id: String
    let table: String
    let schema: String
    let kind: Kind
    let leftRows: Int?
    let rightRows: Int?
}

enum SchemaDiff {

    static func compare(left: [TableInfo], right: [TableInfo]) -> [SchemaDelta] {
        let leftByID  = Dictionary(uniqueKeysWithValues: left.map  { ($0.id, $0) })
        let rightByID = Dictionary(uniqueKeysWithValues: right.map { ($0.id, $0) })
        let allIDs = Set(leftByID.keys).union(rightByID.keys)

        return allIDs.sorted().map { id -> SchemaDelta in
            switch (leftByID[id], rightByID[id]) {
            case (nil, let r?):
                return SchemaDelta(id: id, table: r.name, schema: r.schema,
                                   kind: .added,
                                   leftRows: nil, rightRows: r.estimatedRows)
            case (let l?, nil):
                return SchemaDelta(id: id, table: l.name, schema: l.schema,
                                   kind: .removed,
                                   leftRows: l.estimatedRows, rightRows: nil)
            case (let l?, let r?):
                let kind: SchemaDelta.Kind = (l.estimatedRows == r.estimatedRows) ? .unchanged : .modified
                return SchemaDelta(id: id, table: l.name, schema: l.schema,
                                   kind: kind,
                                   leftRows: l.estimatedRows, rightRows: r.estimatedRows)
            case (nil, nil):
                fatalError("Unreachable: id was harvested from one of the dictionaries")
            }
        }
    }

    /// Compile the diff into a linear list of migration statements that a
    /// DBA could review before applying.
    static func migrationScript(deltas: [SchemaDelta]) -> String {
        var lines: [String] = ["-- Generated by MacTable schema diff", ""]
        for delta in deltas {
            switch delta.kind {
            case .added:
                lines.append("CREATE TABLE \"\(delta.schema)\".\"\(delta.table)\" ( /* columns inferred at runtime */ );")
            case .removed:
                lines.append("DROP TABLE \"\(delta.schema)\".\"\(delta.table)\";")
            case .modified:
                lines.append("-- ALTER \"\(delta.schema)\".\"\(delta.table)\" — review row-count delta (\(delta.leftRows ?? 0) → \(delta.rightRows ?? 0))")
            case .unchanged:
                continue
            }
        }
        return lines.joined(separator: "\n")
    }
}
